# Generated by Django 3.2.8 on 2022-01-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220114_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='Catalogue',
        ),
    ]
