# Generated by Django 3.2.8 on 2022-01-15 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_post_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='post.catalogue')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('comment', models.TextField()),
                ('ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enter', to='post.customerentry')),
            ],
        ),
    ]
